// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: observer/v1/observer.proto

package observerapiconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/jumppad-labs/lattice/pkg/api/observer/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ObserverServiceName is the fully-qualified name of the ObserverService service.
	ObserverServiceName = "observer.v1.ObserverService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ObserverServiceGetTopologyProcedure is the fully-qualified name of the ObserverService's
	// GetTopology RPC.
	ObserverServiceGetTopologyProcedure = "/observer.v1.ObserverService/GetTopology"
	// ObserverServiceWatchTopologyProcedure is the fully-qualified name of the ObserverService's
	// WatchTopology RPC.
	ObserverServiceWatchTopologyProcedure = "/observer.v1.ObserverService/WatchTopology"
	// ObserverServiceGetServiceResourcesProcedure is the fully-qualified name of the ObserverService's
	// GetServiceResources RPC.
	ObserverServiceGetServiceResourcesProcedure = "/observer.v1.ObserverService/GetServiceResources"
	// ObserverServiceGetRequestLogsProcedure is the fully-qualified name of the ObserverService's
	// GetRequestLogs RPC.
	ObserverServiceGetRequestLogsProcedure = "/observer.v1.ObserverService/GetRequestLogs"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	observerServiceServiceDescriptor                   = v1.File_observer_v1_observer_proto.Services().ByName("ObserverService")
	observerServiceGetTopologyMethodDescriptor         = observerServiceServiceDescriptor.Methods().ByName("GetTopology")
	observerServiceWatchTopologyMethodDescriptor       = observerServiceServiceDescriptor.Methods().ByName("WatchTopology")
	observerServiceGetServiceResourcesMethodDescriptor = observerServiceServiceDescriptor.Methods().ByName("GetServiceResources")
	observerServiceGetRequestLogsMethodDescriptor      = observerServiceServiceDescriptor.Methods().ByName("GetRequestLogs")
)

// ObserverServiceClient is a client for the observer.v1.ObserverService service.
type ObserverServiceClient interface {
	// GetTopology returns the current topology snapshot
	GetTopology(context.Context, *connect.Request[v1.GetTopologyRequest]) (*connect.Response[v1.GetTopologyResponse], error)
	// WatchTopology streams topology updates in real-time
	WatchTopology(context.Context, *connect.Request[v1.WatchTopologyRequest]) (*connect.ServerStreamForClient[v1.TopologyUpdate], error)
	// GetServiceResources fetches resource metadata from a Polymorph service via RPC
	GetServiceResources(context.Context, *connect.Request[v1.GetServiceResourcesRequest]) (*connect.Response[v1.GetServiceResourcesResponse], error)
	// GetRequestLogs fetches recent HTTP request logs for a service
	GetRequestLogs(context.Context, *connect.Request[v1.GetRequestLogsRequest]) (*connect.Response[v1.GetRequestLogsResponse], error)
}

// NewObserverServiceClient constructs a client for the observer.v1.ObserverService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewObserverServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ObserverServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &observerServiceClient{
		getTopology: connect.NewClient[v1.GetTopologyRequest, v1.GetTopologyResponse](
			httpClient,
			baseURL+ObserverServiceGetTopologyProcedure,
			connect.WithSchema(observerServiceGetTopologyMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		watchTopology: connect.NewClient[v1.WatchTopologyRequest, v1.TopologyUpdate](
			httpClient,
			baseURL+ObserverServiceWatchTopologyProcedure,
			connect.WithSchema(observerServiceWatchTopologyMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getServiceResources: connect.NewClient[v1.GetServiceResourcesRequest, v1.GetServiceResourcesResponse](
			httpClient,
			baseURL+ObserverServiceGetServiceResourcesProcedure,
			connect.WithSchema(observerServiceGetServiceResourcesMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getRequestLogs: connect.NewClient[v1.GetRequestLogsRequest, v1.GetRequestLogsResponse](
			httpClient,
			baseURL+ObserverServiceGetRequestLogsProcedure,
			connect.WithSchema(observerServiceGetRequestLogsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// observerServiceClient implements ObserverServiceClient.
type observerServiceClient struct {
	getTopology         *connect.Client[v1.GetTopologyRequest, v1.GetTopologyResponse]
	watchTopology       *connect.Client[v1.WatchTopologyRequest, v1.TopologyUpdate]
	getServiceResources *connect.Client[v1.GetServiceResourcesRequest, v1.GetServiceResourcesResponse]
	getRequestLogs      *connect.Client[v1.GetRequestLogsRequest, v1.GetRequestLogsResponse]
}

// GetTopology calls observer.v1.ObserverService.GetTopology.
func (c *observerServiceClient) GetTopology(ctx context.Context, req *connect.Request[v1.GetTopologyRequest]) (*connect.Response[v1.GetTopologyResponse], error) {
	return c.getTopology.CallUnary(ctx, req)
}

// WatchTopology calls observer.v1.ObserverService.WatchTopology.
func (c *observerServiceClient) WatchTopology(ctx context.Context, req *connect.Request[v1.WatchTopologyRequest]) (*connect.ServerStreamForClient[v1.TopologyUpdate], error) {
	return c.watchTopology.CallServerStream(ctx, req)
}

// GetServiceResources calls observer.v1.ObserverService.GetServiceResources.
func (c *observerServiceClient) GetServiceResources(ctx context.Context, req *connect.Request[v1.GetServiceResourcesRequest]) (*connect.Response[v1.GetServiceResourcesResponse], error) {
	return c.getServiceResources.CallUnary(ctx, req)
}

// GetRequestLogs calls observer.v1.ObserverService.GetRequestLogs.
func (c *observerServiceClient) GetRequestLogs(ctx context.Context, req *connect.Request[v1.GetRequestLogsRequest]) (*connect.Response[v1.GetRequestLogsResponse], error) {
	return c.getRequestLogs.CallUnary(ctx, req)
}

// ObserverServiceHandler is an implementation of the observer.v1.ObserverService service.
type ObserverServiceHandler interface {
	// GetTopology returns the current topology snapshot
	GetTopology(context.Context, *connect.Request[v1.GetTopologyRequest]) (*connect.Response[v1.GetTopologyResponse], error)
	// WatchTopology streams topology updates in real-time
	WatchTopology(context.Context, *connect.Request[v1.WatchTopologyRequest], *connect.ServerStream[v1.TopologyUpdate]) error
	// GetServiceResources fetches resource metadata from a Polymorph service via RPC
	GetServiceResources(context.Context, *connect.Request[v1.GetServiceResourcesRequest]) (*connect.Response[v1.GetServiceResourcesResponse], error)
	// GetRequestLogs fetches recent HTTP request logs for a service
	GetRequestLogs(context.Context, *connect.Request[v1.GetRequestLogsRequest]) (*connect.Response[v1.GetRequestLogsResponse], error)
}

// NewObserverServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewObserverServiceHandler(svc ObserverServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	observerServiceGetTopologyHandler := connect.NewUnaryHandler(
		ObserverServiceGetTopologyProcedure,
		svc.GetTopology,
		connect.WithSchema(observerServiceGetTopologyMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	observerServiceWatchTopologyHandler := connect.NewServerStreamHandler(
		ObserverServiceWatchTopologyProcedure,
		svc.WatchTopology,
		connect.WithSchema(observerServiceWatchTopologyMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	observerServiceGetServiceResourcesHandler := connect.NewUnaryHandler(
		ObserverServiceGetServiceResourcesProcedure,
		svc.GetServiceResources,
		connect.WithSchema(observerServiceGetServiceResourcesMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	observerServiceGetRequestLogsHandler := connect.NewUnaryHandler(
		ObserverServiceGetRequestLogsProcedure,
		svc.GetRequestLogs,
		connect.WithSchema(observerServiceGetRequestLogsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/observer.v1.ObserverService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ObserverServiceGetTopologyProcedure:
			observerServiceGetTopologyHandler.ServeHTTP(w, r)
		case ObserverServiceWatchTopologyProcedure:
			observerServiceWatchTopologyHandler.ServeHTTP(w, r)
		case ObserverServiceGetServiceResourcesProcedure:
			observerServiceGetServiceResourcesHandler.ServeHTTP(w, r)
		case ObserverServiceGetRequestLogsProcedure:
			observerServiceGetRequestLogsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedObserverServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedObserverServiceHandler struct{}

func (UnimplementedObserverServiceHandler) GetTopology(context.Context, *connect.Request[v1.GetTopologyRequest]) (*connect.Response[v1.GetTopologyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("observer.v1.ObserverService.GetTopology is not implemented"))
}

func (UnimplementedObserverServiceHandler) WatchTopology(context.Context, *connect.Request[v1.WatchTopologyRequest], *connect.ServerStream[v1.TopologyUpdate]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("observer.v1.ObserverService.WatchTopology is not implemented"))
}

func (UnimplementedObserverServiceHandler) GetServiceResources(context.Context, *connect.Request[v1.GetServiceResourcesRequest]) (*connect.Response[v1.GetServiceResourcesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("observer.v1.ObserverService.GetServiceResources is not implemented"))
}

func (UnimplementedObserverServiceHandler) GetRequestLogs(context.Context, *connect.Request[v1.GetRequestLogsRequest]) (*connect.Response[v1.GetRequestLogsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("observer.v1.ObserverService.GetRequestLogs is not implemented"))
}
